@startuml

skinparam componentStyle rectangle

actor User
folder "items.txt"
folder "logs.txt"

component {
    User .down.> [Ui]
    [BinBash] -left-> [Ui]
    [BinBash] --> [Parser]
    [BinBash] --> [Storage]
    [BinBash] --> [Data]

    [Command] --> [Data]
    [Command] .up.> [Ui]

    [Storage] --> [Data]
    [Storage] .right.> "items.txt"

    [Logger] .right.> "logs.txt"

    [Storage] -[hidden]left- [Parser]
    [Parser] -[hidden]-- [Data]
}

@enduml