@startuml

skinparam componentStyle rectangle
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam CircledCharacterFontSize 0
skinparam CircledCharacterRadius 0

component Data {

    class ItemList {
        - totalRevenue: Double
        - totalCost: Double
        - itemList: ArrayList<Item>
        - sortedOrder: ArrayList<Integer>

        + addItem(): String
        + updateItemDataByName(): String
        + updateItemDataByIndex(): String
        + findItemByName(itemName: String): Item
        + sellOrRestockItem(itemName: String, itemQuantity: Integer, command: String): String
        + deleteItem(): String
        + printList(itemList: List<Item>): String
    }

    class "{abstract}\nItem" {
        # itemName: String
        # itemDescription: String
        # itemQuantity: Integer
        # itemCostPrice: Double

        + getItemName(): String
        + getItemDescription(): String
        + getItemQuantity(): Integer
        + setItemQuantity(itemQuantity: Integer)
        + getItemCostPrice(): Double
    }

    class SearchAssistant {
        - foundItems: ArrayList<Item>

        + setFoundItems(foundItems: ArrayList<Item>): void
        + getFoundItems(): ArrayList<Item>
    }

    SearchAssistant -left-* "1" ItemList

    ItemList --> "*" "{abstract}\nItem" : > contains
}

@enduml