@startuml

skinparam componentStyle rectangle
skinparam linetype ortho

component Data {

    class ItemList {
        - totalRevenue: Double
        - totalCost: Double
        - itemList: ArrayList<Item>
        - sortedOrder: ArrayList<Integer>

        + getTotalRevenue(): Double
        + getTotalCost(): Double
        + getProfitMargin(): String
        + addItem(): String
        + updateItemDataByName(): String
        + updateItemDataByIndex(): String
        + findItemByName(itemName: String): Item
        + sellOrRestockItem(itemName: String, itemQuantity: Integer, command: String): String
        + alertItemQuantity(item: Item): String
        + deleteItem(index: Integer): String
        + deleteItem(keyword: String): String
        + printList(itemList: List<Item>): String
        + printListSortedByCostPrice(itemList: List<Item>): String
        + printListSortedByExpiryDate(itemList: List<Item>): String
        + printListSortedBySalePrice(itemList: List<Item>): String
    }

    abstract class Item {
        # itemName: String
        # itemDescription: String
        # itemQuantity: Integer
        # itemCostPrice: Double

        + getItemName(): String
        + getItemDescription(): String
        + getItemQuantity(): Integer
        + setItemQuantity(itemQuantity: Integer)
        + getItemCostPrice(): Double
        + toString(): String
    }

    class SearchAssistant {
        - foundItems: ArrayList<Item>

        + setFoundItems(foundItems: ArrayList<Item>): void
        + getFoundItems(): ArrayList<Item>
        + getFoundItems(numberOfResults: Integer): ArrayList<Item>
    }

    SearchAssistant -left-* "1" ItemList

    ItemList --> "*" Item : > contains
}

@enduml