@startuml

skinparam linetype ortho

abstract class Item {
    # itemName: String
    # itemDescription: String
    # itemQuantity: Integer
    # itemCostPrice: Double

    + getItemName(): String
    + getItemDescription(): String
    + getItemQuantity(): Integer
    + setItemQuantity(itemQuantity: Integer)
    + getItemCostPrice(): Double
    + toString(): String
}

class OperationalItem {
    + toString(): String
}

class RetailItem {
    - itemSalePrice: Double

    + getItemSalePrice(): Double
    + toString(): String
}

class PerishableOperationalItem{
    - itemExpirationDate: LocalDate

    + getItemExpirationDate(): String
    + toString(): String
}

class PerishableRetailItem {
    - itemExpirationDate: LocalDate

    + getItemExpirationDate(): String
    + toString(): String
}

Item <|-- OperationalItem
Item <|-- RetailItem

OperationalItem <|-- PerishableOperationalItem
RetailItem <|-- PerishableRetailItem

@enduml