
@startuml
hide footbox
actor user
participant ":Ui"
participant ":BinBash"
participant ":Parser"
participant ":Command"
participant ":ItemList"
participant ":Storage"

activate ":BinBash"

loop isUserActive

    ":BinBash" -> ":Ui" : 1. readUserCommand()
    activate ":Ui"
    user -> ":Ui" : 'list'
    return 2. userInput:String ('list')

    ":BinBash" -> ":Parser" : 3. parseCommand('list')
    activate ":Parser"
    return 4. userCommand:Command

    ":BinBash" -> ":Command" : 5. execute()
    activate ":Command"
    ":Command" -> ":ItemList" : 6. printList()
    activate ":ItemList"
    return 7. executionUiOutput:String
    return

    ":BinBash" -> ":Command" : 8. getExecutionUiOutput()
    activate ":Command"
    return 9. outputString:String

    ":BinBash" -> ":Ui" : 10. talk(outputString)
    activate ":Ui"
    ":Ui" --> user : 11. outputString
    return

    opt hasToSave
        ":BinBash" -> ":Storage" : 12. saveToStorage()
        activate ":Storage"
        return
    end

end

@enduml
