@startuml

skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam CircledCharacterFontSize 0
skinparam CircledCharacterRadius 0

class XYZCommandParser {
    + parse(commandArgs: String[]): XYZCommand
}

package "Apache Commons CLI" #DDDDDD {
        class DefaultParser {
            + parse(options: Options, arguments: String[]): CommandLine
        }

        class Options

        class CommandLine {
            # options : Options
            + getOptionValue(): String
            + getOptionValues(): String[]
        }
}

DefaultParser -d- "cmd" CommandLine : > stores option values in
XYZCommandParser -up-|> DefaultParser
DefaultParser "1" *-left- Options
XYZCommandParser -u-> CommandLine : gets option values from >
@enduml
