@startuml

skinparam classAttributeIconSize 0
skinparam CircledCharacterFontSize 0
skinparam CircledCharacterRadius 0

class BinBash {

    - userInterface : Ui
    - itemList : ItemList
    - inputParser : Parser
    - storage : Storage
    - logger : BinBashLogger

    + {method} BinBash()
    - {method} run()
    + {static} main(args : String[])

}

class Storage {

    # filePath : String
    # dataDirectoryPath : String
    # dataFileName : String
    # isCorrupted : boolean
    # storageLogger : BinBashLogger

    + {method} Storage()
    + {method} loadData() : ArrayList<Item>
    - {method} handleCorruptedFile()
    - {method} renameCorruptedFile() : boolean
    - {method} createNewTxtFile() : boolean
    # {method} readTxtFile() : ArrayList<String>
    # {method} parseLinesToItemList(stringRepresentationOfTxtFile : ArrayList<String>) : ArrayList<Item>
    # {method} convertLineToItem(line : String) : Item
    + {method} saveToStorage(itemList : List<Item>)
    # {method} generateTextToSave(itemList : List<Item>) : String
    # {method} generateStorageRepresentationOfSingleItem(item : Item) : String

}

BinBash --> Storage : uses
@enduml
